# Generated by Django 2.0.13 on 2019-08-02 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('lugar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Lugar')),
                ('grama', models.BooleanField(default=False)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('backend.lugar',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('lugar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Lugar')),
                ('italiano', models.BooleanField(default=False)),
                ('chino', models.BooleanField(default=False)),
            ],
            bases=('backend.lugar',),
        ),
    ]
