# Generated by Django 2.0.13 on 2019-08-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.SmallIntegerField()),
                ('antirabica', models.BooleanField(default=False)),
                ('desparasitante', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.SmallIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('tamanio', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
