# Generated by Django 2.0.13 on 2019-08-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190801_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('producido', models.DateTimeField(auto_now_add=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['nombre'],
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
            ],
            options={
                'verbose_name': 'ProductoInventario',
                'indexes': [],
                'ordering': ['producido'],
                'proxy': True,
                'verbose_name_plural': 'ProductoInventarios',
            },
            bases=('backend.producto',),
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
            ],
            options={
                'verbose_name': 'ProductoVenta',
                'indexes': [],
                'ordering': ['precio'],
                'proxy': True,
                'verbose_name_plural': 'ProductoVentas',
            },
            bases=('backend.producto',),
        ),
    ]
