# Generated by Django 2.0.13 on 2019-08-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_producto_productoinventario_productoventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoInventario',
        ),
        migrations.DeleteModel(
            name='ProductoVenta',
        ),
    ]
