# Generated by Django 2.0.13 on 2019-08-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_createdupdatedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatedUpdatedModel',
        ),
    ]
