# Generated by Django 2.0.13 on 2019-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
