# Generated by Django 2.0.13 on 2019-08-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190820_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('rol', models.SmallIntegerField(choices=[(1, 'DOCENTE'), (2, 'ESTUDIANTE')], null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.NullBooleanField()),
                ('carnet', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'ordering': ['nombre'],
            },
            bases=('backend.persona',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'ordering': ['carnet'],
            },
            bases=('backend.persona',),
        ),
    ]
